ppc64le-cloud/jenkins-infra

- hack/load-all-job.sh
- vars/pullSecret.groovy
Also, avoided creating node clean up job. This would be removed later
> Changing Pull secret as sting credential

- jobs/pipelines/powervs/ocp-4.8/daily-ocp4.8-powervs-saopaulo01-p9-min/Jenkinsfile
- jobs/pipelines/powervs/stability-check/daily-powervs-saopaulo01-p9-stability-check/Jenkinsfile
https://jenkins.ppc64le-cloud.org/job/powervs/job/ocp-4.8/job/daily-ocp4.8-powervs-saopaulo01-p9-min/6
> Fixing sao paulo failure 4.8

- hack/jjb_template.jinja2
- jobs/pipelines/powervs/ocp-4.5/daily-ocp4.5-powervs-script-saopaulo-01-p9-min/Jenkinsfile
- jobs/pipelines/powervs/ocp-4.6/daily-ocp4.6-powervs-script-saopaulo01-p9-min/Jenkinsfile
- jobs/pipelines/powervs/ocp-4.7/daily-ocp4.7-powervs-script-osaka21-p9-min/Jenkinsfile
- jobs/pipelines/powervs/ocp-4.8/daily-ocp4.8-powervs-osaka21-p9-min/Jenkinsfile
- jobs/pipelines/powervs/ocp-4.8/daily-ocp4.8-powervs-osaka21-p9-scale/Jenkinsfile
- jobs/pipelines/powervs/poll-powervs-images/Jenkinsfile
- jobs/pipelines/powervs/stability-check/daily-powervs-osaka21-p9-stability-check/Jenkinsfile
The pvsadm issue is resolved with https://github.com/ppc64le-cloud/pvsadm/releases/tag/v0.1.1-alpha.5
> Adding jobs in Saopaulo and Osaka

- deploy/makefiles/Makefile.openshift4_pvs_script
- vars/dbDashboardUpdateE2e.groovy
- vars/dbDashboardUpdateScale.groovy
This also fix error
https://jenkins.ppc64le-cloud.org/job/powervs/job/ocp-4.6/job/daily-ocp4.6-powervs-script-saopaulo01-p9-min/2/console
```
make[1]: *** [makefiles/Makefile.openshift4_pvs_script:25: deploy:openshift4:powervs:script:output] Error 255
make: *** [Makefile:165: deploy-openshift4-powervs-script:output] Error 2
[platform_checks] ERROR: Unsupported Linux distribution
```
> Updating db field ocp-build

- jobs/pipelines/mirror-openshift-release/Jenkinsfile
- scripts/mirror-images.sh
IKS Supports only containerd (https://www.ibm.com/cloud/blog/ibm-cloud-kubernetes-service-supports-containerd)
> Using nerdctl cli

- vars/deployCluster.groovy
Job Link :https://jenkins.ppc64le-cloud.org/job/powervs/job/ocp-4.7/job/daily-ocp4.7-powervs-script-osaka21-p9-min/3/console
> Adding temp fix for script files

- jobs/pipelines/powervs/poll-powervs-images/Jenkinsfile
- jobs/pipelines/powervs/stability-check/daily-powervs-dallas-p9-stability-check/Jenkinsfile
- jobs/pipelines/powervs/stability-check/daily-powervs-dallas12-p9-stability-check/Jenkinsfile
- jobs/pipelines/powervs/stability-check/daily-powervs-frankfurt01-p9-stability-check/Jenkinsfile
- jobs/pipelines/powervs/stability-check/daily-powervs-frankfurt02-p9-stability-check/Jenkinsfile
- jobs/pipelines/powervs/stability-check/daily-powervs-london-p9-stability-check/Jenkinsfile
- jobs/pipelines/powervs/stability-check/daily-powervs-osaka21-p9-stability-check/Jenkinsfile
- jobs/pipelines/powervs/stability-check/daily-powervs-saopaulo01-p9-stability-check/Jenkinsfile
- jobs/pipelines/powervs/stability-check/daily-powervs-sydney-p9-stability-check/Jenkinsfile
- jobs/pipelines/powervs/stability-check/daily-powervs-tokyo-p9-stability-check/Jenkinsfile
- jobs/pipelines/powervs/stability-check/daily-powervs-toronto-p9-stability-check/Jenkinsfile
- jobs/pipelines/powervs/stability-check/daily-powervs-washington-p9-stability-check/Jenkinsfile
Stability Job Link: https://jenkins.ppc64le-cloud.org/job/temp-folder-testing-jobs/job/jenkins-backup/14/
> Changing image to rhel-84

- README.md
- docs/BACKUP_README.md
- hack/ibmcloud-build-pod.yaml
- hack/jjb_template.jinja2
- images/ibmcloud-backup-image/Dockerfile
- jobs/pipelines/daily-jenkins-backup-job/Jenkinsfile
- jobs/pipelines/restore-backup/Jenkinsfile
- scripts/backup.sh
- scripts/restore-backup.sh
Backup Job Run https://jenkins.ppc64le-cloud.org/job/temp-folder-testing-jobs/job/jenkins-backup/13/console
> Initial commit jenkins backup

- jobs/pipelines/powervs/powervs-image-create-and-upload-job/Jenkinsfile
- scripts/convert-upload-image-powervs.sh
Job Link:https://jenkins.ppc64le-cloud.org/job/temp-folder-testing-jobs/job/jenkins-backup/16/console
> Fixing Image upload job

- jobs/pipelines/powervm/ocp-4.8/daily-ocp4.8-powervm-p8-min/Jenkinsfile
- jobs/pipelines/powervm/ocp-4.8/daily-ocp4.8-powervm-p9-max/Jenkinsfile
- jobs/pipelines/powervm/ocp-4.8/daily-ocp4.8-powervm-p9-min-sriov/Jenkinsfile
- jobs/pipelines/powervs/ocp-4.8/daily-ocp4.8-powervs-dallas12-p9-min/Jenkinsfile
- jobs/pipelines/powervs/ocp-4.8/daily-ocp4.8-powervs-london-p9-min/Jenkinsfile
- jobs/pipelines/powervs/ocp-4.8/daily-ocp4.8-powervs-osaka21-p9-min/Jenkinsfile
- jobs/pipelines/powervs/ocp-4.8/daily-ocp4.8-powervs-saopaulo01-p9-min/Jenkinsfile
- jobs/pipelines/powervs/ocp-4.8/daily-ocp4.8-powervs-sydney-p9-min/Jenkinsfile
- jobs/pipelines/powervs/ocp-4.8/daily-ocp4.8-powervs-tokyo-p9-min/Jenkinsfile
- jobs/pipelines/powervs/ocp-4.8/daily-ocp4.8-powervs-toronto-p9-min/Jenkinsfile
- jobs/pipelines/powervs/ocp-4.8/daily-ocp4.8-powervs-washington-p9-min/Jenkinsfile
Changed E2e repo and Go lang version to 1.16.5 For 4.8 jobs
> Reverting changes for 4.8 E2e run and changing Go Lang version

- hack/jjb_template.jinja2
- jobs/pipelines/powervs/ocp-4.9/daily-ocp4.9-powervs-toronto-p9-min/Jenkinsfile
- jobs/pipelines/powervs/poll-powervs-images/Jenkinsfile
- vars/getOpenshiftBuild.groovy
- vars/getOpenshiftClient.groovy
> Adding 4.9 job

- files/cerberus-config.yaml
- files/custom_check_res_usage.py
- jobs/pipelines/powervs/ocp-4.9/ocp4.9-powervs-montreal01-p9-longevity/Jenkinsfile
- jobs/pipelines/powervs/poll-powervs-images/Jenkinsfile
- scripts/cron.sh
- vars/cerberusSetup.groovy
-Created longevity test
-Changed cron script to be compatible with powervs
> Enabling OCP4.9 pipeline for longevity test

- hack/jjb_template.jinja2
- jobs/pipelines/powervm/ocp-4.10/daily-ocp4.10-powervm-p9-extproxy-min/Jenkinsfile
- scripts/capture-artifacts-ocp4.sh
> Disabling proxy job

- scripts/cron.sh
Added some additional commands to cron script suggested by Piyush which helps in collecting information about the cluster.
FYI : @juliemathew @Shilpi-Das1
> Update cron script with new commands

- jobs/pipelines/powervm/zstreams/zstream-ocp4x-p8-min-current-upgrade/Jenkinsfile
- jobs/pipelines/powervm/zstreams/zstream-ocp4x-p8-min-direct-deploy/Jenkinsfile
- jobs/pipelines/powervm/zstreams/zstream-ocp4x-p8-min-next-upgrade/Jenkinsfile
- jobs/pipelines/powervm/zstreams/zstream-trigger-job/Jenkinsfile
This PR include Jenkins files for zstream deployment automation:
- zstream-trigger-job
- zstream-ocp4x-p8-min-direct-deploy
- zstream-ocp4x-p8-min-current-upgrade
- zstream-ocp4x-p8-min-next-upgrade
> Adding Zstream Automation Jenkinsfiles

- jobs/pipelines/powervm/custom-powervm-jobs/custom-ocp4x-p8-min-two-upgrades/Jenkinsfile
- vars/setupAndUpgrade.groovy
This PR includes:
- OCP Z Stream two upgrades (eg. 4.8.27->4.9.17->4.10.0-fc.2)
> Added Jenkinsfile for two upgrades

- jobs/pipelines/mirror-openshift-release/Jenkinsfile
> Removed 4.3,4.4 and 4.5 from mirror job added 4.11

- jobs/pipelines/powervm/ocp-4.10/daily-ocp4.10-powervm-p10-min/Jenkinsfile
- jobs/pipelines/powervm/ocp-4.10/daily-ocp4.10-powervm-p10-ovn-min/Jenkinsfile
- jobs/pipelines/powervm/ocp-4.10/daily-ocp4.10-powervm-p10-ssp-min/Jenkinsfile
- jobs/pipelines/powervm/ocp-4.10/daily-ocp4.10-powervm-p8-ovn-min/Jenkinsfile
- jobs/pipelines/powervm/ocp-4.10/daily-ocp4.10-powervm-p9-max/Jenkinsfile
- jobs/pipelines/powervm/ocp-4.10/daily-ocp4.10-powervm-p9-min/Jenkinsfile
- jobs/pipelines/powervm/ocp-4.11/daily-ocp4.11-powervm-p10-max/Jenkinsfile
- jobs/pipelines/powervm/ocp-4.11/daily-ocp4.11-powervm-p10-ovn-min/Jenkinsfile
- jobs/pipelines/powervm/ocp-4.11/daily-ocp4.11-powervm-p10-sriov-min/Jenkinsfile
- jobs/pipelines/powervm/ocp-4.11/daily-ocp4.11-powervm-p10-ssp-min/Jenkinsfile
- jobs/pipelines/powervm/ocp-4.11/daily-ocp4.11-powervm-p10-vscsi-min/Jenkinsfile
- jobs/pipelines/powervm/ocp-4.11/daily-ocp4.11-powervm-p9-max/Jenkinsfile
- jobs/pipelines/powervm/ocp-4.7/daily-ocp4.7-powervm-p9-min/Jenkinsfile
- jobs/pipelines/powervm/ocp-4.8/daily-ocp4.8-powervm-p9-min/Jenkinsfile
- jobs/pipelines/powervm/ocp-4.9/daily-ocp4.9-powervm-p10-min/Jenkinsfile
- jobs/pipelines/powervm/ocp-4.9/daily-ocp4.9-powervm-p9-min/Jenkinsfile
Changed host groups
Change E2e file for ovn specific test
> change p10 host group to p10 pvm and p9 host group to p9_pvm

- jobs/pipelines/powervm/custom-powervm-jobs/custom-ocp4.x-powervm-upgrade/Jenkinsfile
- jobs/pipelines/powervm/custom-powervm-jobs/custom-ocp4x-powervm-two-upgrades/Jenkinsfile
- Added `ChoiceParameter` for HostGroup.
- Used `validatingString` plugin for validating string parameters.
Signed-off-by: varad-ahirwadkar <varad.ahirwadkar@ibm.com>
> Updating PowerVC custom upgrade jobs 

- hack/jjb_template.jinja2
- jobs/pipelines/powervs/ocp-4.11/daily-ocp4.11-powervs-sydney04-p9-min/Jenkinsfile
- jobs/pipelines/powervs/poll-powervs-images/Jenkinsfile
- jobs/pipelines/powervs/stability-check/daily-powervs-sydney-p9-stability-check/Jenkinsfile
Moved jobs from syd 04
Changed schedule of daily-ocp4.10-powervs-sydney04-p9-lates as it conflict with stability job
> Moving jobs from syd 04

- jobs/pipelines/powervs/zstreams/zstream-ocp4x-powervs-toronto01-p9-current-upgrade/Jenkinsfile
- jobs/pipelines/powervs/zstreams/zstream-ocp4x-powervs-toronto01-p9-min-direct-deploy/Jenkinsfile
- jobs/pipelines/powervs/zstreams/zstream-ocp4x-powervs-toronto01-p9-min-next-upgrade/Jenkinsfile
This PR contains three z stream job's Jenkinsfile for PowerVS toronto01 service instance.
- Direct deployment (eg. 4.8.45)
- Current Upgrade  (eg. 4.8.45 -> 4.8.46)
- Next Upgrade  (eg. 4.8.46 -> 4.9.42)
> Adding Z stream jobs for PowerVS

- vars/deployCluster.groovy
Spliting reboot into three sets and adding sleep time individually
> Updating sleep time

- jobs/pipelines/powervs/ipi-4.11/daily-ipi4.11-powervs-london06/Jenkinsfile
- jobs/pipelines/powervs/ipi-4.11/daily-ipi4.11-powervs-osaka21/Jenkinsfile
- jobs/pipelines/powervs/ipi-4.11/daily-ipi4.11-powervs-toronto01/Jenkinsfile
- jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-london06/Jenkinsfile
- jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-toronto01/Jenkinsfile
This fix is needed until https://github.com/hamzy/powervs-hack/blob/main/scripts/create-cluster.sh get fixed for latest changes
> Making changes according to the updated json output

- hack/jjb_template.jinja2
- jobs/pipelines/powervs/ocp-4.12/daily-ocp4.12-powervs-verification-tests-script-sydney05-p9-min/Jenkinsfile
- scripts/capture-artifacts-ocp4.sh
- scripts/verification.sh
To enable a job for running smoke tests of Verification-tests.
> Add verification test job

- deploy/Makefile
- deploy/templates/.deploy-openshift4-powervs-script.tfvars.template
- hack/jjb_template.jinja2
- jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-lon06-tier-2/Jenkinsfile
- jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-lon06-tier-4b/Jenkinsfile
- jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-1/Jenkinsfile
- jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-3/Jenkinsfile
- jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-4c/Jenkinsfile
- jobs/pipelines/powervs/poll-powervs-images/Jenkinsfile
- vars/odfAuthYaml.groovy
- vars/odfProcessTierTestResults.groovy
- vars/odfRunCommands.groovy
- vars/odfRunSetupScript.groovy
- vars/setupClusterConfig.groovy
- vars/setupCommonEnvironmentVariables.groovy
@sudeeshjohn For automation to work we need to add the following credentials to jenkins:
1. ODF_IBMCLOUD_API_KEY
2. PULL_SECRET --> Add odf related tokens to the existing pull secret
3. ODF_AUTH_YAML
> Adding odf 4.12 deployment automation

- jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-lon06-tier-2/Jenkinsfile
- jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-lon06-tier-4b/Jenkinsfile
- jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-1/Jenkinsfile
- jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-3/Jenkinsfile
- jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-4c/Jenkinsfile
> Fixing artifactory path

- jobs/pipelines/powervs/odf/zstreams/zstream-odf4.x-powervs-syd05-upgrade/Jenkinsfile
- scripts/capture-artifacts-ocp4.sh
- vars/odfRunCommands.groovy
- vars/odfRunSetupScript.groovy
Adding job for Z-stream ODF upgrade Jobs. 
Signed-off-by: Aaruni Aggarwal <aaruniagg@gmail.com>
> Adding upgrade z-stream job

- scripts/verification.sh
Signed-off-by: Aishwarya Kamat <aishwarya.kamat@ibm.com>
> Modify verification test job to support ppc64le tags

- jobs/pipelines/powervs/ocp-4.12/daily-ocp4.12-powervs-script-sydney05-p9-smoke/Jenkinsfile
Increased the ssh timeout to fix "client_loop: send disconnect: Broken pipe" issue
> Increased the ssh timeout

- hack/jjb_template.jinja2
- jobs/pipelines/powervm/ocp-4.10/daily-ocp4.10-powervm-p9-max/Jenkinsfile
- jobs/pipelines/powervm/ocp-4.10/daily-ocp4.10-powervm-p9-min/Jenkinsfile
- jobs/pipelines/powervm/ocp-4.11/daily-ocp4.11-powervm-p9-min/Jenkinsfile
- jobs/pipelines/powervm/ocp-4.12/daily-ocp4.12-powervm-p10-vscsi-min/Jenkinsfile
- jobs/pipelines/powervm/ocp-4.12/daily-ocp4.12-powervm-p9-sriov-min/Jenkinsfile
- jobs/pipelines/powervm/ocp-4.12/daily-ocp4.12-powervm-p9-ssp-min/Jenkinsfile
- jobs/pipelines/powervm/ocp-4.8/daily-ocp4.8-powervm-p8-min/Jenkinsfile
- jobs/pipelines/powervm/ocp-4.8/daily-ocp4.8-powervm-p9-min/Jenkinsfile
- jobs/pipelines/powervm/ocp-4.9/daily-ocp4.9-powervm-p9-min/Jenkinsfile
- jobs/pipelines/powervs/ocp-4.11/daily-ocp4.11-powervs-script-sydney05-p9-latest/Jenkinsfile
- vars/setupCommonEnvironmentVariables.groovy
Changed scg_id to c2663d7f-2e81-4698-abc4-dca631220f7d for all jobs
For Vscsi and p9 jobs changed it to 8a5ff38d-0e88-40bd-8bc3-2d1434789461
> Change scg id and fix small issues

- hack/jjb_template.jinja2
This PR removes the schedule for daily-ocp4.12-powervs-script-sydney05-p9-smoke  in scheduler.
> Remove schedule for daily-ocp4.12-powervs-script-sydney05-p9-smoke job

- hack/jjb_template.jinja2
- jobs/pipelines/powervm/ocp/4.12/daily-ocp4.12-powervm-p8-verification/Jenkinsfile
Signed-off-by: Aishwarya Kamat <aishwarya.kamat@ibm.com>
> Add verification test job on PowerVC

- hack/jjb_template.jinja2
- jobs/pipelines/powervm/ocp/4.13/daily-ocp4.13-powervm-p9-sdn-min/Jenkinsfile
- jobs/pipelines/powervm/ocp/4.13/daily-ocp4.13-powervm-p9-vscsi/Jenkinsfile
- jobs/pipelines/powervm/odf/4.12/daily-odf4.12-powervm-p9-tier-1/Jenkinsfile
- jobs/pipelines/powervm/odf/4.12/daily-odf4.12-powervm-p9-tier-2/Jenkinsfile
- jobs/pipelines/powervm/odf/4.12/daily-odf4.12-powervm-p9-tier-4c/Jenkinsfile
This PR updates the hardware version from p10 to p9 for powervm in 4.13 pipelines.
> Change p10 to p9

- deploy/templates/.deploy-openshift4-powervc.tfvars.template
- deploy/templates/.deploy-openshift4-powervs-script.tfvars.template
- deploy/templates/.deploy-openshift4-powervs.tfvars.template
- jobs/pipelines/powervm/ocp/4.10/daily-ocp4.10-to-4.11-powervm-p8-min-upgrade/Jenkinsfile
- jobs/pipelines/powervm/ocp/4.11/daily-ocp4.11-to-4.12-powervm-p8-min-upgrade/Jenkinsfile
- jobs/pipelines/powervm/ocp/4.13/daily-ocp4.13-powervm-p9-vscsi/Jenkinsfile
- vars/setupCommonEnvironmentVariables.groovy
This PR -
1. Adds upgrade pause and delay variable default values.
2. Removes vars from powervc and powervs terraform templates.
> Change upgrade related environment vars

- jobs/pipelines/powervs/ocp/4.12/daily-ocp4.12-powervs-script-montreal01-p9-scale/Jenkinsfile
- jobs/pipelines/powervs/ocp/4.12/daily-ocp4.12-powervs-script-sydney05-p9-min/Jenkinsfile
- jobs/pipelines/powervs/ocp/4.12/daily-ocp4.12-powervs-script-sydney05-p9-smoke/Jenkinsfile
This PR  changes the artifact version to main for PowerVS jobs which are using master.
> Change Artifact Version for powervs jobs

- jobs/pipelines/powervm/ocp/4.11/daily-ocp4.11-to-4.12-powervm-p8-min-upgrade/Jenkinsfile
> change  latest-${OCP_RELEASE}-build.txt to latest-${OCP_RELEASE}-stable-build.txt

- hack/jjb_template.jinja2
- jobs/pipelines/powervm/odf/4.13/daily-odf4.13-powervm-p9-tier-1/Jenkinsfile
- jobs/pipelines/powervm/odf/4.13/daily-odf4.13-powervm-p9-tier-2/Jenkinsfile
- jobs/pipelines/powervm/odf/4.13/daily-odf4.13-powervm-p9-tier-3/Jenkinsfile
- jobs/pipelines/powervm/odf/4.13/daily-odf4.13-powervm-p9-tier-4b/Jenkinsfile
- jobs/pipelines/powervm/odf/4.13/daily-odf4.13-powervm-p9-tier-4c/Jenkinsfile
- vars/odfRunSetupScript.groovy
This PR creates odf 4.13 pipelines and their schedule.
> Create ODF 4.13 CI pipelines

- jobs/pipelines/powervm/odf/zstreams/zstream-odf4.x-p9-powervm-upgrade/Jenkinsfile
- jobs/pipelines/powervs/odf/zstreams/zstream-odf4.x-powervs-syd05-upgrade/Jenkinsfile
- jobs/pipelines/powervs/poll-powervs-images/Jenkinsfile
- vars/odfRunSetupScript.groovy
Updating z-stream ODF job to clone the ocs-upi-kvm repository according to ODF version and update the ocs-ci-conf file for tier testing 
Signed-off-by: Aaruni Aggarwal [aaruniagg@gmail.com](mailto:aaruniagg@gmail.com)
> Updating z-stream ODF job 

- hack/jjb_template.jinja2
- jobs/pipelines/powervm/odf/4.13/daily-odf4.13-powervm-p9-tier-1/Jenkinsfile
- jobs/pipelines/powervm/odf/4.13/daily-odf4.13-powervm-p9-tier-3/Jenkinsfile
- jobs/pipelines/powervm/odf/zstreams/zstream-odf4.x-p9-powervm-upgrade/Jenkinsfile
- jobs/pipelines/powervs/odf/zstreams/zstream-odf4.x-powervs-syd05-upgrade/Jenkinsfile
- scripts/odf/fix-config.sh
- vars/odfRunSetupScript.groovy
- vars/setupClusterConfig.groovy
- Reduced ODF resource usage for Master nodes (using OCP's min req)
- Moved ODF configuration update to script from Jenkinsfile
- Updated schedule 
- Moved all ODF CI jobs to p9_odf group
> Updating cluster config and ODF upgrade script

- jobs/pipelines/powervm/odf/4.13/daily-odf4.13-powervm-p9-tier-1/Jenkinsfile
- jobs/pipelines/powervm/odf/4.13/daily-odf4.13-powervm-p9-tier-2/Jenkinsfile
- jobs/pipelines/powervm/odf/4.13/daily-odf4.13-powervm-p9-tier-3/Jenkinsfile
- jobs/pipelines/powervm/odf/4.13/daily-odf4.13-powervm-p9-tier-4b/Jenkinsfile
- jobs/pipelines/powervm/odf/4.13/daily-odf4.13-powervm-p9-tier-4c/Jenkinsfile
> Enabling vault

- hack/jjb_template.jinja2
- jobs/pipelines/powervm/ocp/4.12/daily-ocp4.12-to-4.13-powervm-p9-min-upgrade/Jenkinsfile
This PR,
Creates  daily-ocp4.12-to-4.13-powervm-p9-min-upgrade pipeline and adds schedule for it.
Tested on molly.
> Create 4.12 to 4.13 upgrade pipeline on p9

- scripts/verification.sh
> To remove the forked repo changes in the verification script

- images/jenkins-inbound-agent/Dockerfile
- jobs/pipelines/powervm/odf/4.13/daily-odf4.13-powervm-p9-tier-1/Jenkinsfile
- jobs/pipelines/powervm/odf/4.13/daily-odf4.13-powervm-p9-tier-2/Jenkinsfile
- jobs/pipelines/powervm/odf/4.13/daily-odf4.13-powervm-p9-tier-3/Jenkinsfile
- jobs/pipelines/powervm/odf/4.13/daily-odf4.13-powervm-p9-tier-4b/Jenkinsfile
- jobs/pipelines/powervm/odf/4.13/daily-odf4.13-powervm-p9-tier-4c/Jenkinsfile
- jobs/pipelines/powervm/odf/zstreams/zstream-odf4.x-p9-powervm-upgrade/Jenkinsfile
- scripts/capture-artifacts-ocp4.sh
- scripts/odf/fix-config.sh
- scripts/odf/run-odf-deploy.sh
- scripts/odf/run-odf-upgrade.sh
- scripts/odf/run-tier-tests.sh
- vars/odfRunCommands.groovy
- vars/odfRunSetupScript.groovy
This patch is enabling the ODF env to trigger deployment and tests from the container itself
Other updates
1. Updated ibmcloud version
> Run on container

- hack/jjb_template.jinja2
- jobs/pipelines/mirror-openshift-release/Jenkinsfile
- jobs/pipelines/powervm/ocp/4.14/daily-ocp4.14-powervm-p9-min/Jenkinsfile
- jobs/pipelines/powervm/ocp/4.14/weekly-ocp4.14-powervm-p9-croo/Jenkinsfile
- jobs/pipelines/powervm/ocp/4.14/weekly-ocp4.14-powervm-p9-sdn-min/Jenkinsfile
- jobs/pipelines/powervm/ocp/4.14/weekly-ocp4.14-powervm-p9-sriov/Jenkinsfile
- jobs/pipelines/powervm/ocp/4.14/weekly-ocp4.14-powervm-p9-verification/Jenkinsfile
- jobs/pipelines/powervm/ocp/4.14/weekly-ocp4.14-powervm-p9-vscsi/Jenkinsfile
- jobs/pipelines/powervm/poll-powervc-images/Jenkinsfile
- vars/setupCommonEnvironmentVariables.groovy
Created the Jenkins files PowerVC  jobs for ocp-4.14
- updated `env.OCP_RELEASE = 4.14` and `REDHAT_RELEASE = "9.2"`
- Renamed 4.13 scheduled builds to 4.14  in `jjb_template.jinja2`
- Updated 4.14 and 9.2 info in `poll-powervc-images` and `mirror-openshift-release` jenkinsfiles
- Updated `GO` Version from `1.19` to `1.20`
Review the below files:
```
hack/jjb_template.jinja2
jobs/pipelines/mirror-openshift-release/Jenkinsfile
jobs/pipelines/powervm/ocp/4.14/daily-ocp4.14-powervm-p9-min/Jenkinsfile
jobs/pipelines/powervm/ocp/4.14/weekly-ocp4.14-powervm-p9-sdn-min/Jenkinsfile
jobs/pipelines/powervm/ocp/4.14/weekly-ocp4.14-powervm-p9-sriov/Jenkinsfile
jobs/pipelines/powervm/ocp/4.14/weekly-ocp4.14-powervm-p9-verification/Jenkinsfile …
```
> Create PowerVC  jobs for ocp-4.14

- jobs/pipelines/powervm/ocp/4.14/daily-ocp4.14-powervm-p9-min/Jenkinsfile
chnaged library  name  from `poorna-library@pvc-14`to` jenkins-upstream-library`
> Changed library name to jenkins-upstream-library

- hack/jjb_template.jinja2
- jobs/pipelines/powervs/ocp/4.14/daily-ocp4.14-powervs-script-p9-min/Jenkinsfile
- jobs/pipelines/powervs/poll-powervs-images/Jenkinsfile
- vars/setupCommonEnvironmentVariables.groovy
Created the Jenkins files PowerVS jobs for ocp-4.14
updated `env.OCP_RELEASE = 4.14` , `BASTION_IMAGE = "rhel-92"`  and `RHCOS_IMAGE = "rhcos-414"`
Replaced `4.13` scheduled builds with  `4.14` in jjb_template.jinja2
Updated `rhcos 4.14` and `rhel 9.2` info in poll-powervc-images jenkinsfile
Updated GO Version from `1.19` to `1.20`
Review the below files:
```
hack/jjb_template.jinja2
jobs/pipelines/mirror-openshift-release/Jenkinsfile
jobs/pipelines/powervs/ocp/4.14/daily-ocp4.14-powervs-script-p9-min/Jenkinsfile
vars/setupCommonEnvironmentVariables.groovy
```
> adding powervs ocp4.14 jobs

- hack/jjb_template.jinja2
- jobs/pipelines/powervs/ipi/4.14/daily-ipi4.14-powervs-london06/Jenkinsfile
- jobs/pipelines/powervs/ipi/4.14/daily-ipi4.14-powervs-montreal01/Jenkinsfile
- jobs/pipelines/powervs/ipi/4.14/daily-ipi4.14-powervs-osaka21/Jenkinsfile
- jobs/pipelines/powervs/ipi/4.14/daily-ipi4.14-powervs-sydney05/Jenkinsfile
- vars/setupCommonEnvironmentVariables.groovy
Added ocp-4.14 ipi jobs.
updated `OCP_RELEASE = "4.14"`
> adding ipi ocp-4.14 jobs

- jobs/pipelines/powervm/odf/zstreams/zstream-odf4.x-p9-powervm-upgrade/Jenkinsfile
- jobs/pipelines/powervs/odf/zstreams/zstream-odf4.x-powervs-syd05-upgrade/Jenkinsfile
Adding rhcos and rhel images in powervs and powervm z-stream ODF jobs
> Adding rhcos and rhel image for 4.14 in z-stream jobs of odf

- hack/jjb_template.jinja2
This PR for splitting the schedule for IPI jobs
the jobs will run every 12 hrs. and updated schedule to run the jobs one after another(for each region) for every 12 hrs.
> 4.14 IPI job schedule changes

- hack/jjb_template.jinja2
- jobs/pipelines/powervm/odf/4.14/daily-odf4.14-powervm-p9-tier-1/Jenkinsfile
- jobs/pipelines/powervm/odf/4.14/daily-odf4.14-powervm-p9-tier-2/Jenkinsfile
- jobs/pipelines/powervm/odf/4.14/daily-odf4.14-powervm-p9-tier-3/Jenkinsfile
- jobs/pipelines/powervm/odf/4.14/daily-odf4.14-powervm-p9-tier-4b/Jenkinsfile
- jobs/pipelines/powervm/odf/4.14/daily-odf4.14-powervm-p9-tier-4c/Jenkinsfile
- vars/odfRunSetupScript.groovy
> created ODF 4.14 OCP jobs

- vars/setupCommonEnvironmentVariables.groovy
> reverting mtu patch

- jobs/pipelines/mirror-openshift-release/Jenkinsfile
- scripts/mirror-images.sh
Changed from `sys-powercloud-docker-local.artifactory.swg-devops.com/...` to `docker-na.artifactory.swg-devops.com/sys-powercloud-docker-local/...`
> Updated Docker Registry URL

- jobs/pipelines/mirror-openshift-release/Jenkinsfile
- jobs/pipelines/powervm/ocp/4.14/weekly-ocp4.14-to-4.15-powervm-p9-min-upgrade/Jenkinsfile
- jobs/pipelines/powervm/odf/4.14/daily-odf4.14-powervm-p9-tier-1/Jenkinsfile
- jobs/pipelines/powervm/odf/4.14/daily-odf4.14-powervm-p9-tier-2/Jenkinsfile
- jobs/pipelines/powervm/odf/4.14/daily-odf4.14-powervm-p9-tier-3/Jenkinsfile
- jobs/pipelines/powervm/odf/4.14/daily-odf4.14-powervm-p9-tier-4b/Jenkinsfile
- jobs/pipelines/powervm/odf/4.14/daily-odf4.14-powervm-p9-tier-4c/Jenkinsfile
- scripts/verification.sh
- Added rc builds for 4.14 for upgrade jobs.
- Added fix verification job e2e failures
- Updated odf jobs pull secrets ID to `PULL_SECRET ` from `ODF_PULL_SECRET`
> Added temporary fixes for the deploy and e2e issues.

- deploy/Makefile
- deploy/templates/.deploy-openshift4-powervc.tfvars.template
- deploy/templates/.deploy-openshift4-powervs-script.tfvars.template
- jobs/pipelines/powervm/ocp/4.14/daily-ocp4.14-powervm-p9-min/Jenkinsfile
- jobs/pipelines/powervm/ocp/4.15/daily-ocp4.15-powervm-p9-min/Jenkinsfile
- jobs/pipelines/powervs/ocp/4.14/daily-ocp4.14-powervs-script-p9-min/Jenkinsfile
- jobs/pipelines/powervs/poll-powervs-images/Jenkinsfile
- scripts/capture-artifacts-ocp4.sh
- scripts/kdump/kdump_gather_logs.sh
- vars/gatherKdumpLogs.groovy
- Enabled kdump for ocp 4.14 and 4.15 daily jobs on powervc and powervs
- Added the stage for collecting kdump logs if any.
> Enable kdump in ocp 4.14 and 4.15 daily jobs on PowerVC and PowerVS

- hack/jjb_template.jinja2
- jobs/pipelines/mirror-openshift-release/Jenkinsfile
- scripts/mirror-images.sh
- Updated `nerdctl `command with `docker`
- Disabled IPI 4.14 job on Tok04
- Disabled odf 4.14 jobs temporarily
> Added fix for docker push temporarily

- jobs/pipelines/powervm/ocp/custom-powervm-jobs/custom-ocp4-deploy-1/Jenkinsfile
Reverts ppc64le-cloud/jenkins-infra#313
> Revert "remove custom job"

- hack/jjb_template.jinja2
- jobs/pipelines/mirror-openshift-release/Jenkinsfile
- jobs/pipelines/powervm/ocp/4.13/weekly-ocp4.13-to-4.14-powervm-p9-min-upgrade/Jenkinsfile
- jobs/pipelines/powervm/ocp/4.14/weekly-ocp4.14-powervm-p9-vscsi/Jenkinsfile
- jobs/pipelines/powervm/ocp/4.14/weekly-ocp4.14-to-4.15-powervm-p9-min-upgrade/Jenkinsfile
- jobs/pipelines/powervm/ocp/4.15/weekly-ocp4.15-powervm-p9-sdn-min/Jenkinsfile
- jobs/pipelines/powervm/ocp/4.15/weekly-ocp4.15-powervm-p9-verification/Jenkinsfile
- jobs/pipelines/powervm/ocp/4.15/weekly-ocp4.15-to-4.16-powervm-p9-min-upgrade/Jenkinsfile
- jobs/pipelines/powervm/ocp/4.16/daily-ocp4.16-powervm-p9-min/Jenkinsfile
- jobs/pipelines/powervm/ocp/4.16/weekly-ocp4.16-powervm-p9-sdn-min/Jenkinsfile
- jobs/pipelines/powervm/ocp/4.16/weekly-ocp4.16-powervm-p9-sriov/Jenkinsfile
- jobs/pipelines/powervm/ocp/4.16/weekly-ocp4.16-powervm-p9-verification/Jenkinsfile
- jobs/pipelines/powervm/ocp/4.16/weekly-ocp4.16-powervm-p9-vscsi/Jenkinsfile
- jobs/pipelines/powervm/poll-powervc-images/Jenkinsfile
- jobs/pipelines/powervs/ipi/4.15/daily-ipi4.15-powervs-frankfurt1/Jenkinsfile
- jobs/pipelines/powervs/ipi/4.15/daily-ipi4.15-powervs-frankfurt2/Jenkinsfile
- jobs/pipelines/powervs/ipi/4.15/daily-ipi4.15-powervs-madrid02/Jenkinsfile
- jobs/pipelines/powervs/ipi/4.15/daily-ipi4.15-powervs-madrid04/Jenkinsfile
- jobs/pipelines/powervs/ipi/4.15/daily-ipi4.15-powervs-saopaulo04/Jenkinsfile
- jobs/pipelines/powervs/ipi/4.15/daily-ipi4.15-powervs-washingtondc06/Jenkinsfile
- jobs/pipelines/powervs/ipi/4.15/daily-ipi4.15-powervs-washingtondc07/Jenkinsfile
- jobs/pipelines/powervs/ocp/4.15/daily-ocp4.15-powervs-script-p9-min/Jenkinsfile
- jobs/pipelines/powervs/ocp/4.16/daily-ocp4.16-powervs-script-p9-min/Jenkinsfile
- jobs/pipelines/powervs/poll-powervs-images/Jenkinsfile
- vars/setupCommonEnvironmentVariables.groovy
- Enabling 4.16 ocp jobs
- Enabling 4.15 ocp and IPI jobs
> Enabling 4.16, 4.15 ocp jobs and 4.15 ipi jobs

- jobs/pipelines/powervm/odf/4.16/daily-odf4.16-powervm-p9-tier-1/Jenkinsfile
- jobs/pipelines/powervm/odf/4.16/daily-odf4.16-powervm-p9-tier-2/Jenkinsfile
- jobs/pipelines/powervm/odf/4.16/daily-odf4.16-powervm-p9-tier-3/Jenkinsfile
- jobs/pipelines/powervm/odf/4.16/daily-odf4.16-powervm-p9-tier-4b/Jenkinsfile
- jobs/pipelines/powervm/odf/4.16/daily-odf4.16-powervm-p9-tier-4c/Jenkinsfile
- vars/odfRunSetupScript.groovy
- Updated odf jobs with below details:
```
REDHAT_RELEASE = "9.3"
OCP_RELEASE = "4.16"
ODF_VERSION = "4.16"
OS_PRIVATE_NETWORK="icp_network4"
OS_NETWORK="icp_network4"
NETWORK_TYPE = "SRIOV" set to null
CNI_NETWORK_PROVIDER = "OpenshiftSDN"  set to  "OVNKubernetes"
```
> Enabling 4.16 odf jobs

- hack/jjb_template.jinja2
- vars/odfRunSetupScript.groovy
- Disabled 4.15 and 4.16 OpenshiftSDN jobs.
- Fix typo in odfRunSetupScript for odf 4.16 jobs
> Disabled 4.15/4.16 OpenshiftSDN jobs

- jobs/pipelines/mirror-openshift-release/Jenkinsfile
- jobs/pipelines/powervm/ocp/4.12/weekly-ocp4.12-to-4.13-powervm-p9-min-upgrade/Jenkinsfile
- jobs/pipelines/powervm/ocp/4.13/weekly-ocp4.13-powervm-p9-min/Jenkinsfile
- jobs/pipelines/powervm/ocp/4.15/weekly-ocp4.15-to-4.16-powervm-p9-min-upgrade/Jenkinsfile
- jobs/pipelines/powervm/ocp/custom-powervm-jobs/custom-ocp4.x-powervm-p9-deploy-croo-metallb/Jenkinsfile
- jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p8-min/zstream-ocp4x-p8-min-current-upgrade/Jenkinsfile
- jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p8-min/zstream-ocp4x-p8-min-direct-deploy/Jenkinsfile
- jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p8-min/zstream-ocp4x-p8-min-next-upgrade/Jenkinsfile
- jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p8-min/zstream-p8-trigger-job/Jenkinsfile
- jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p9-min/zstream-ocp4x-p9-min-current-upgrade/Jenkinsfile
- jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p9-min/zstream-ocp4x-p9-min-direct-deploy/Jenkinsfile
- jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p9-min/zstream-ocp4x-p9-min-next-upgrade/Jenkinsfile
- jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p9-min/zstream-p9-trigger-job/Jenkinsfile
- scripts/capture-artifacts-ocp4.sh
- scripts/cron.sh
- Enabling the zstream jobs from 4.12 to 4.16.
- added few fixes for job failure's.
- Added some command output for oc version and os release
> Enable zstream jobs on on-prem

- hack/jjb_template.jinja2
- jobs/pipelines/powervm/ocp/4.17/weekly-ocp4.17-powervm-p9-npiv/Jenkinsfile
- vars/processE2eResults.groovy
PowerVC jobs are failing while processing the e2e results and its failing to send slack notification with new inbound agent image as its having the latest scp version.
- With latest new Jenkins inbound agent image while running the scp command for junit_e2e*.xml files it is creating the directory  (junit_e2e.xml) if there are multiple source files, hence its failing to run sed commands on directory.
> Updated the e2e process code for filtering the latest Junit_e2e*.xml files.

- hack/jjb_template.jinja2
- jobs/pipelines/mirror-openshift-release/Jenkinsfile
- jobs/pipelines/powervm/ocp/4.16/weekly-ocp4.16-to-4.17-powervm-p9-min-upgrade/Jenkinsfile
- jobs/pipelines/powervm/poll-powervc-images/Jenkinsfile
- jobs/pipelines/utility-jobs/powervs-ipi-cleanup-job/Jenkinsfile
- scripts/cleanup-ipi-resources.sh
- Created an IPI cleanup job that runs daily and cleans up IPI resources which were created during IPI jobs.
- Updated mirror-job and poll-powervc jobs.
- Updated the powervc upgrade job build to rc build( 4.16-stable to 4.17-rc).
> Add IPI cleanup scheduled job and fix job failures.

- jobs/pipelines/powervm/ocp/custom-powervm-jobs/custom-ocp4.x-powervm-p9-deploy-operator-tests/Jenkinsfile
- scripts/capture-artifacts-ocp4.sh
- scripts/operator/fio_operator.sh
Automating CI pipeline for FIO operator
> FIO_changes

- jobs/pipelines/powervm/odf/4.18/odf4.18-powervm-p9-scale/Jenkinsfile
- scripts/capture-artifacts-ocp4.sh
- scripts/odf/run-tier-tests.sh
- vars/odfProcessTierTestResults.groovy
- vars/odfRunSetupScript.groovy
- vars/setupClusterConfig.groovy
- vars/setupCommonEnvironmentVariables.groovy
> Adding scale test

- hack/jjb_template.jinja2
- jobs/pipelines/powervm/odf/4.19/odf4.19-powervm-p9-tier-1-buffer-io-disabled/Jenkinsfile
- jobs/pipelines/powervm/odf/4.19/odf4.19-powervm-p9-tier-1/Jenkinsfile
- jobs/pipelines/powervm/odf/4.19/odf4.19-powervm-p9-tier-2/Jenkinsfile
- jobs/pipelines/powervm/odf/4.19/odf4.19-powervm-p9-tier-3/Jenkinsfile
- jobs/pipelines/powervm/odf/4.19/odf4.19-powervm-p9-tier-4a/Jenkinsfile
- jobs/pipelines/powervm/odf/4.19/odf4.19-powervm-p9-tier-4b/Jenkinsfile
- jobs/pipelines/powervm/odf/4.19/odf4.19-powervm-p9-tier-4c/Jenkinsfile
- scripts/odf/buffer_io_disabled.sh
- scripts/odf/check_crc.sh
- scripts/odf/odf-build-info.sh
- scripts/odf/run-tier-tests.sh
- vars/odfRunCommands.groovy
- Added CRC logs
- Collected Must gather
- Added job for buffer IO disabled
-  Made changes for tier-2 execution
> Made changes for ODF builds

- hack/jjb_template.jinja2
- jobs/pipelines/powervs/ocp/4.10/daily-ocp4.10-powervs-sydney04-p9-latest/Jenkinsfile
- jobs/pipelines/powervs/ocp/4.11/daily-ocp4.11-powervs-script-sydney05-p9-latest/Jenkinsfile
- jobs/pipelines/powervs/poll-powervs-images/Jenkinsfile
- jobs/pipelines/powervs/powervs-image-create-and-upload-job/Jenkinsfile
- jobs/pipelines/powervs/stability-check/daily-powervs-dallas-p9-stability-check/Jenkinsfile
- jobs/pipelines/powervs/stability-check/daily-powervs-dallas12-p9-stability-check/Jenkinsfile
- jobs/pipelines/powervs/stability-check/daily-powervs-frankfurt01-p9-stability-check/Jenkinsfile
- jobs/pipelines/powervs/stability-check/daily-powervs-frankfurt02-p9-stability-check/Jenkinsfile
- jobs/pipelines/powervs/stability-check/daily-powervs-london-04-p9-stability-check/Jenkinsfile
- jobs/pipelines/powervs/stability-check/daily-powervs-london-06-p9-stability-check/Jenkinsfile
- jobs/pipelines/powervs/stability-check/daily-powervs-montreal01-p9-stability-check/Jenkinsfile
- jobs/pipelines/powervs/stability-check/daily-powervs-osaka21-p9-stability-check/Jenkinsfile
- jobs/pipelines/powervs/stability-check/daily-powervs-saopaulo01-p9-stability-check/Jenkinsfile
- jobs/pipelines/powervs/stability-check/daily-powervs-sydney-p9-stability-check/Jenkinsfile
- jobs/pipelines/powervs/stability-check/daily-powervs-tokyo-p9-stability-check/Jenkinsfile
- jobs/pipelines/powervs/stability-check/daily-powervs-toronto-p9-stability-check/Jenkinsfile
- jobs/pipelines/powervs/stability-check/daily-powervs-washington-p9-stability-check/Jenkinsfile
- jobs/pipelines/utility-jobs/powervs-cleanup-job/Jenkinsfile
- jobs/pipelines/utility-jobs/powervs-ipi-cleanup-job/Jenkinsfile
- scripts/cleanup-powervs-resources.sh
- vars/initializeEnvironment.groovy
- Updated pvsadm version to Latest
- Updated PowerVS cleanup job code for UPI and enabled the schedule for cleanup.
> Update pvsadm version to latest and updating the code

- jobs/pipelines/mirror-openshift-release/Jenkinsfile
- jobs/pipelines/powervm/ocp/4.19/weekly-ocp4.19-to-4.20-powervm-p9-min-upgrade/Jenkinsfile
- jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p9-min/zstream-ocp4x-p9-min-current-upgrade/Jenkinsfile
- jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p9-min/zstream-ocp4x-p9-min-direct-deploy/Jenkinsfile
- jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p9-min/zstream-ocp4x-p9-min-next-upgrade/Jenkinsfile
- vars/setupCommonEnvironmentVariables.groovy
Update mirror job
Update 4.20 ec builds to rc
> Update zstream rhcos image details for 4.20
